### PR TITLE
Keep selected forced device after close app

### PR DESCRIPTION
**Pull request by mikigal**
Keep selected forced device after close app with UserDefaults

### CODE REVIEW

**Comment by milgra** [comment]
Cool, thank you very much! :)

**Comment by tyrann0us** [comment]
Hi @milgra, any chance to create a release for this? I have no experience in building the app myself.
Thanks!

**Comment by stormychel** [comment]
@tyrann0us I can provide you with a binary or instructions how to build (not that hard), will follow up when I’m back at office.

**Comment by stormychel** [comment]
@tyrann0us Even easier, I noticed there is a binary for downloading right here: https://github.com/milgra/airpodssoundqualityfixer/releases/tag/1.0

**Comment by tyrann0us** [comment]
Hi @stormychel, that release (`1.0`) does not include the fix from this PR. Also see this diff: https://github.com/milgra/airpodssoundqualityfixer/compare/1.0...master

BTW, I can highly recommend https://github.com/refined-github/refined-github because it does great things like this:
Bildschirmfoto 2022-11-15 um 14 40 04

**Comment by stormychel** [comment]
Thanks for the tip, added that to my reading list :)

Yes I see now, other version, will compile a version and put a link here.

**Comment by stormychel** [comment]
Ok here goes: https://github.com/stormychel/https-github.com-stormychel-airpodssoundqualityfixer/releases/tag/release

@milgra if you have any issues with this, let me know and I will take it down again.

**Comment by ilqvya** [comment]
image

**Comment by stormychel** [comment]
Sorry this was Private, should be fixed now.
https://github.com/stormychel/https-github.com-stormychel-airpodssoundqualityfixer/releases/tag/release

**Pull request merged**
