### PR TITLE
Implement hide menu icon feature

### PR DESCRIPTION
**Pull request by avalko**

### CODE REVIEW

**Comment by stormychel** [comment]
Works but not sure whether this is useful, how do we get the icon back? :)

**Comment by caminashell** [comment]
A keyboard shortcut.

**Comment by neseleznev** [comment]
> Works but not sure whether this is useful, how do we get the icon back? :)

Via the Launchpad, Spotlight, or Finder

image

**Comment by neseleznev** [comment]
@avalko could you please add the binary to your repo's releases or just attach it here?

**Comment by stormychel** [comment]
> @avalko could you please add the binary to your repo's releases or just attach it here?

I have some releases on my fork: https://github.com/stormychel/https-github.com-stormychel-airpodssoundqualityfixer

**Comment by MarshalX** [comment]
> > @avalko could you please add the binary to your repo's releases or just attach it here?
> 
> I have some releases on my fork: https://github.com/stormychel/https-github.com-stormychel-airpodssoundqualityfixer

tbh it doesn't work for me on 13.4.1 (c). it starts (i see the active process in the activity monitor), but there is no icon at the bar. maybe due to mdm/antivirus on my working machine. idk

**Comment by stormychel** [comment]
Hmm strange, it’s been very stable to me, even works on the Sonoma beta’s.
Can you try compiling from source and check console for any issues?

**Pull request merged**
